// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8DeP6vU9_FIusiSFdRSPaNzp_FQWKT_E',
    appId: '1:615082195352:web:874903782e17de3f7d53ed',
    messagingSenderId: '615082195352',
    projectId: 'resq-b1cb9',
    authDomain: 'resq-b1cb9.firebaseapp.com',
    storageBucket: 'resq-b1cb9.appspot.com',
    measurementId: 'G-XNDTQ1W7ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPH9DGmvGeQExSTfdVGLvVG8toLJmvDck',
    appId: '1:615082195352:android:d2d05dd682cd01077d53ed',
    messagingSenderId: '615082195352',
    projectId: 'resq-b1cb9',
    storageBucket: 'resq-b1cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiW6o0kjIuXco41Ts5VsdWTqcs7da0lkg',
    appId: '1:615082195352:ios:f606794c7026a66e7d53ed',
    messagingSenderId: '615082195352',
    projectId: 'resq-b1cb9',
    storageBucket: 'resq-b1cb9.appspot.com',
    iosBundleId: 'com.example.assignmentSaleheen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiW6o0kjIuXco41Ts5VsdWTqcs7da0lkg',
    appId: '1:615082195352:ios:6a22a02458639f087d53ed',
    messagingSenderId: '615082195352',
    projectId: 'resq-b1cb9',
    storageBucket: 'resq-b1cb9.appspot.com',
    iosBundleId: 'com.example.assignmentSaleheen.RunnerTests',
  );
}
